# Generated by Django 4.0.2 on 2022-04-14 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_remove_comment_check_start_date_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='commentvote',
            constraint=models.UniqueConstraint(fields=('user', 'comment'), name='unique_vote_per_user_for_comments'),
        ),
    ]
