# Generated by Django 4.0.2 on 2022-03-16 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0004_postvote_unique_vote_per_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
