# Generated by Django 4.0.2 on 2022-03-23 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0005_post_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='real_name',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
